cookbookApp/cookbookApp/urls.py
from django.contrib import admin
from django.urls import path, include
from list_recipes import views
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('addViaLink/', views.AddAutomatic.as_view(), name="add with link"),
    path('addManually/', views.AddManually.as_view(), name="add manually"),
    path('', views.Index.as_view(), name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path(r'test/<title>', views.Test.as_view(), name="test"),
    path(r'addImage/<title>', views.addImage, name="addImage"),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.UserRegistration.as_view(), name="register")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cookbookApp/list_recipes/urls.py
from django.urls import path
from list_recipes import views

urlpatterns = [
    path('', views.home, name='home'),
]

cookbookApp/list_recipes/models.py
from django.db import models
from django.contrib.auth.models import  User

# Create your models here.
class Recipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    instructions = models.CharField(max_length=10000, default="")
    time = models.IntegerField(default=-1)
    title = models.CharField(max_length=50)
    recipe_yield = models.CharField(max_length=50, default="")
    original_url = models.CharField(max_length=200, default="")

class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient_info = models.CharField(max_length=100)

class RecipeImage(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    image_title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')

class Employee(models.Model):
    name = models.CharField(max_length=150)
    position = models.CharField(max_length=150)
    office = models.CharField(max_length=150)
    age = models.PositiveIntegerField()
    start_date = models.DateField()
    salary = models.PositiveIntegerField()


    def __str__(self):
        return self.name

cookbookApp/list_recipes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class UrlForm(forms.Form):
    url = forms.URLField(label='url')

class CreateRecipeForm(forms.Form):
    title = forms.CharField(label="title")
    recipe_yield = forms.CharField(label="recipe_yield", required=False)
    time = forms.IntegerField(label="time", required=False)
    instructions = forms.CharField(label="instructions", widget=forms.Textarea, required=False)

class ImageForm(forms.Form):
    title = forms.CharField(max_length=100)
    image = forms.ImageField()

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(label="first_name")
    last_name = forms.CharField(label="last_name")
    email = forms.CharField(widget=forms.EmailInput)
    
class IngredientForm(forms.Form):
    ingredient = forms.CharField(label="ingredient", required=False)

cookbookApp/list_recipes/views.py
from django.shortcuts import render
from list_recipes.forms import UrlForm, CreateRecipeForm, UserRegistrationForm
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms.formsets import formset_factory
from .models import Employee, Recipe, Ingredient, RecipeImage
from .forms import CreateRecipeForm, ImageForm, IngredientForm, UrlForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from recipe_scrapers import scrape_me, WebsiteNotImplementedError
import logging

def addImage(request, title):
    def addImage():
        form = ImageForm(request.POST, request.FILES)
        recipe = Recipe.objects.filter(user = request.user).get(title = title)
        ingredients = Ingredient.objects.filter(recipe = recipe)
        if form.is_valid():
            image_title = form.cleaned_data['title']
            image = form.cleaned_data['image']
            RecipeImage.objects.create(recipe=recipe, image_title = image_title, image=image)
        logging.debug('invalid form:')
        logging.debug(form.errors)

    if request.method == 'POST':
        addImage()
    return HttpResponseRedirect('/test/' + title)

# Create your views here.
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

class Index(LoginRequiredMixin, View):
    template = 'index.html'
    login_url = '/login/'

    def get(self, request):
        IngredientFormSet = formset_factory(IngredientForm)
        recipes = Recipe.objects.filter(user = request.user)
        return render(request, self.template, {'recipes': recipes, 'formset': IngredientFormSet()})

    def post(self, request):
        IngredientFormSet = formset_factory(IngredientForm)
        ingredients = IngredientFormSet(request.POST)
        if ingredients.is_valid():
            recipes = Recipe.objects.filter(user = request.user)
            for ingredient_form in ingredients:
                if ingredient_form.is_valid() and ingredient_form.cleaned_data.get('ingredient'):
                    recipes = recipes.filter(ingredient__ingredient_info__icontains=ingredient_form.cleaned_data.get('ingredient'))
                    logging.debug(recipes)
            return render(request, self.template, {'recipes': recipes.distinct(), 'formset': ingredients})
        return self.get(request)

class AddAutomatic(LoginRequiredMixin, View):
    template = 'addAutomatic.html'
    login_url = '/login/'
    WEBSITE_NOT_IMPLEMENTED = "Cooking Journal cannot currently extract recipes from this website!"
    RECIPE_EXISTS = "Recipe with the same title exists!"

    def get(self, request):
        form = UrlForm()
        return render(request, self.template, {'form': form})

    def post(self, request):
        url = request.POST.get('url', None)
        if url is not None:
           try:
               scraper = scrape_me(url)
               existing_recipe = Recipe.objects.filter(user = request.user).get(original_url = url)
               return render(request, self.template, {'form': UrlForm(request.POST), "success": False, "errorReason": self.RECIPE_EXISTS}) #with error
           except Recipe.DoesNotExist:
               new_recipe = Recipe.objects.create(user = request.user, instructions = scraper.instructions(), time = scraper.total_time(), title = scraper.title(), recipe_yield = scraper.yields(), original_url = url)
               for ingredient_description in scraper.ingredients():
                   new_ingredient = Ingredient.objects.create(recipe=new_recipe, ingredient_info=ingredient_description)
                   logging.debug("ingredient: {0}".format(ingredient_description))
               return render(request, self.template, {'form': UrlForm(), "success": True})
           except WebsiteNotImplementedError:
               return render(request, self.template, {'form': UrlForm(request.POST), "success": False, "errorReason": self.WEBSITE_NOT_IMPLEMENTED})

class AddManually(LoginRequiredMixin, View):
    template = 'addManually.html'
    login_url = '/login/'
    RECIPE_EXISTS = "Recipe with the same title exists!"
    INVALID_TITLE = "Please choose a different name!"

    def get(self, request):
        form = CreateRecipeForm()
        IngredientFormSet = formset_factory(IngredientForm)
        return render(request, self.template, {'formset': IngredientFormSet(), 'form': form})

    def post(self, request):
        IngredientFormSet = formset_factory(IngredientForm)
        ingredients = IngredientFormSet(request.POST)
        title = request.POST.get('title', "")
        recipe_yield = request.POST.get("recipe_yield", None)
        time = request.POST.get("time", "")
        if len(time) == 0:
            time = -1
        else:
            time = int(time)
        instructions = request.POST.get("instructions", None)
        if len(title) > 0:
           try:
               existing_recipe = Recipe.objects.filter(user = request.user).get(title = title)
               return render(request, self.template, {'formset': IngredientFormSet(request.POST), 'form': CreateRecipeForm(request.POST), "success": False, "errorReason": self.RECIPE_EXISTS}) #with error bc title already exists
           except Recipe.DoesNotExist:
               new_recipe = Recipe.objects.create(user = request.user, time=time, instructions = instructions, title = title, recipe_yield = recipe_yield)
               for ingredient_form in ingredients:
                   if ingredient_form.is_valid() and ingredient_form.cleaned_data.get('ingredient'):
                       new_ingredient = Ingredient.objects.create(recipe=new_recipe, ingredient_info=ingredient_form.cleaned_data.get('ingredient'))
               return render(request, self.template, {'formset': IngredientFormSet(), 'form': CreateRecipeForm(), "success": True})
        else:
            return render(request, self.template, {'formset': IngredientFormSet(request.POST), 'form': CreateRecipeForm(request.POST), "success": False, "errorReason": self.INVALID_TITLE}) #with error bc invalid name

class Login(View):
    template = 'login.html'

    def get(self, request):
        form = AuthenticationForm()
        return render(request, self.template, {'form': form})


    def post(self, request):
        form = AuthenticationForm(request.POST)
        username = request.POST.get('username', "")
        password = request.POST.get('password', "")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            return render(request, self.template, {'form': form, 'login_failed': True})

class Test(View):
    template = 'testing.html'

    def get(self, request, title):
        recipe = Recipe.objects.filter(user = request.user).get(title = title)
        ingredients = Ingredient.objects.filter(recipe = recipe)
        images = RecipeImage.objects.filter(recipe = recipe)
        edit_recipe_form = CreateRecipeForm(initial={'title': recipe.title, 'time': recipe.time, 'recipe_yield': recipe.recipe_yield, 'instructions': recipe.instructions})
        IngredientFormSet = formset_factory(IngredientForm)
        ingredientForms = IngredientFormSet(initial=[{'ingredient': ingredient.ingredient_info} for ingredient in ingredients])
        recipe.instructions = recipe.instructions.split('\n')
        return render(request, self.template, {'images': images, 'recipe': recipe, 'ingredients': ingredients, 'image_upload_form': ImageForm(), 'edit_recipe_form': edit_recipe_form, 'ingredient_formset': ingredientForms})

    def post(self, request, title):
        form = CreateRecipeForm(request.POST)
        IngredientFormSet = formset_factory(IngredientForm)
        ingredient_forms = IngredientFormSet(request.POST)
        def updateRecipe():
            time = int(request.POST['time']) if len(request.POST['time']) > 0 else -1
            existing_recipe = Recipe.objects.filter(user = request.user).get(title = title)
            existing_recipe.title = request.POST['title']
            existing_recipe.recipe_yield = request.POST['recipe_yield']
            existing_recipe.time = time
            existing_recipe.instructions = request.POST['instructions']
            existing_recipe.save()

        def updateIngredients():
            existing_recipe = Recipe.objects.filter(user = request.user).get(title = title)
            new_ingredients = [ingredient_form.cleaned_data.get('ingredient') for ingredient_form in ingredient_forms if ingredient_form.is_valid() and ingredient_form.cleaned_data.get('ingredient')]
            existing_ingredient_objects = Ingredient.objects.filter(recipe = existing_recipe)
            existing_ingredients = [ingredient.ingredient_info for ingredient in existing_ingredient_objects]
            to_add = [ingredient for ingredient in new_ingredients if ingredient not in existing_ingredients]
            to_delete = [ingredient for ingredient in existing_ingredients if ingredient not in new_ingredients]
            for ingredient in to_add:
                Ingredient.objects.create(recipe=existing_recipe, ingredient_info=ingredient)
            existing_ingredient_objects.filter(ingredient_info__in=to_delete).delete()

        if form.is_valid():
            updateRecipe()
            updateIngredients()
        return self.get(request, title)

class UserRegistration(View):
    template = "UserRegistration.html"
    PASSWORD_MISMATCH = "Passwords don't match!"
    INVALID_FIELDS = "Invalid fields. Please try again!"
    USERNAME_IN_USE = "A user with this name already exists!"
    EMAIL_IN_USE = "This email has already been associated with another account!"

    def get(self, request):

cookbookApp/list_recipes/templates/addAutomatic.html
{% extends "navbar_base.html" %}

{% block title %}Add Recipe{% endblock %}

{% block links %}
<!-- Custom fonts for this template-->
<link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

<!-- Custom styles for this template-->
<link href="/static/css/sb-admin.css" rel="stylesheet">
{% endblock %}
{% block content %}
<body class="bg-dark">

  <div class="container">
    {% if errorReason %}
    <div class="alert alert-danger" role="alert">
      {{ errorReason }}
    </div>
    {% elif success %}
    <div class="alert alert-success" role="alert">
      Recipe successfully created!
    </div>
    {% endif %}
    <div class="card mx-auto mt-5">
      <div class="card-header">Add Recipe Via Link</div>
      <div class="card-body">
        <form method="post" action="/addViaLink/">
            {% csrf_token %}
          <label for="id_url"> Recipe Link: </label>
          <div class="form-group">
            <div class="form-label-group">
              {{ form.url }}
            </div>
          </div>
          <button class="btn btn-primary btn-block" type="submit">Add Recipe</button>
        </form>
      </div>
    </div>
  </div>

  <script>
    document.getElementById("id_url").classList.add("form-control");
    document.getElementById("id_url").placeholder = "Username";
    document.getElementById("id_url").type = "text";
    document.getElementById("id_url").required = "required";
    document.getElementById("id_url").autofocus = "autofocus";
  </script>
  <!-- Bootstrap core JavaScript -->
  <!-- <script src="/static/vendor/jquery/jquery.min.js"></script> -->
  <!-- <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script> -->

  <!-- Core plugin JavaScript-->
  <!-- <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script> -->

</body>
{% endblock %}

cookbookApp/list_recipes/templates/addManually.html
{% extends "navbar_base.html" %}

{% block title %}Add Recipe{% endblock %}

{% block links %}
<!-- Custom fonts for this template-->
<link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

<!-- Custom styles for this template-->
<link href="/static/css/sb-admin.css" rel="stylesheet">
{% endblock %}
{% block content %}
<body class="bg-dark">

  <div class="container">
    {% if errorReason %}
    <div class="alert alert-danger" role="alert">
      {{ errorReason }}
    </div>
    {% elif success %}
    <div class="alert alert-success" role="alert">
      Recipe successfully created!
    </div>
    {% endif %}
    <div class="card mx-auto mt-5">
      <div class="card-header">Add Recipe Manually</div>
      <div class="card-body">
        <form method="post" action="/addManually/">
            {% csrf_token %}
          <div class="form-group">
            <label for="id_title"> Recipe Title: </label>
            <div class="form-label-group">
              {{ form.title }}
            </div>
            <label for="id_time"> Recipe Time (in minutes): </label>
            <div class="form-label-group">
              {{ form.time }}
            </div>
            <label for="id_recipe_yield"> Recipe Yield: </label>
            <div class="form-label-group">
              {{ form.recipe_yield }}
            </div>
            <label for="#formset_container"> Ingredients: </label>
            <div id="formset_container" class="form-label-group">
              {{ formset.management_form }}
              {% for ingredient_form in formset %}
                  <div class="ingredient-form py-1">
                      {{ ingredient_form.ingredient }}
                  </div>
              {% endfor %}
              <button id="add-form" class="btn btn-primary" type="button">Add Another Ingredient</button>
            </div>
            <label for="id_instructions"> Instructions (enter each step on a new line): </label>
            <div class="form-label-group">
              {{ form.instructions }}
            </div>
          </div>
          <button class="btn btn-primary btn-block" type="submit">Add Recipe</button>
        </form>
      </div>
    </div>
  </div>

  <script>
    document.getElementById("id_title").classList.add("form-control");
    document.getElementById("id_title").autofocus = "autofocus";
    document.getElementById("id_time").classList.add("form-control");
    document.getElementById("id_recipe_yield").classList.add("form-control");
    document.getElementById("id_instructions").classList.add("form-control");
  </script>
  <!-- Bootstrap core JavaScript -->
  <!-- <script src="/static/vendor/jquery/jquery.min.js"></script> -->
  <!-- <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script> -->

  <!-- Core plugin JavaScript-->
  <!-- <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script> -->

  <script>
    let allForm = document.querySelectorAll(".ingredient-form")
    let container = document.querySelector("#formset_container")
    let addButton = document.querySelector("#add-form")
    let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
    let formNum = allForm.length-1
    addButton.addEventListener('click', addForm)
    for (var i = 0; i < allForm.length; i++) {
      document.getElementById("id_form-" + i + "-ingredient").classList.add("form-control")
    }

    function addForm(e) {
        e.preventDefault()

        let newForm = allForm[0].cloneNode(true) //Clone the bird form
        let formRegex = RegExp(`form-(\\d){1}-`,'g') //Regex to find all instances of the form number

        formNum++ //Increment the form number
        newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`) //Update the new form to have the correct form number
        container.insertBefore(newForm, addButton) //Insert the new form at the end of the list of forms
        document.getElementById("id_form-" + formNum + "-ingredient").classList.add("form-control");
        document.getElementById("id_form-" + formNum + "-ingredient").value = "";
        totalForms.setAttribute('value', `${formNum+1}`) //Increment the number of total forms in the management form
      }
  </script>

</body>
{% endblock %}

cookbookApp/list_recipes/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="/static/css/base.css" rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="/static/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

  {% block links %}
  {% endblock %}

</head>

{% block body %}
{% endblock %}

</html>

cookbookApp/list_recipes/templates/login.html
{% extends "base.html" %}

{% block title %}Dashboard Login{% endblock %}

{% block links %}
<!-- Custom fonts for this template-->
<link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

<!-- Custom styles for this template-->
<link href="/static/css/sb-admin.css" rel="stylesheet">
{% endblock %}
{% block body %}
<body class="bg-dark">

  <div class="container my-4">
    {% if login_failed %}
    <div class="alert alert-danger my-4" role="alert">
      Invalid username or password,.
    </div>
    {% endif %}
    <div class="card card-login mx-auto">
      <div class="card-header">Login</div>
      <div class="card-body">
        <form method="post" action="/login/">
            {% csrf_token %}
          <div class="form-group">
            <div class="form-label-group">
              {{ form.username }}
            </div>
          </div>
          <div class="form-group">
            <div class="form-label-group">
              {{ form.password }}
            </div>
          </div>
          <button class="btn btn-primary btn-block" type="submit">Login</button>
        </form>
        <div class="text-center">
          <a class="d-block small mt-3" href="register.html">Register an Account</a>
          <a class="d-block small" href="forgot-password.html">Forgot Password?</a>
        </div>
      </div>
    </div>
  </div>

  <script>
    document.getElementById("id_username").classList.add("form-control");
    document.getElementById("id_password").classList.add("form-control");
    document.getElementById("id_username").placeholder = "Username";
    document.getElementById("id_password").placeholder = "Password";
    document.getElementById("id_username").type = "text";
    document.getElementById("id_password").type = "password";
    document.getElementById("id_username").required = "required";
    document.getElementById("id_password").required = "required";
    document.getElementById("id_username").autofocus = "autofocus";
  </script>
  <!-- Bootstrap core JavaScript-->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

</body>
{% endblock %}

cookbookApp/list_recipes/templates/testing.html
{% extends "navbar_base.html" %}

{% block title %}Test Page{% endblock %}

{% block links %}
<!-- Custom fonts for this template-->
<link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

<!-- Custom styles for this template-->
<link href="/static/css/sb-admin.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
      {{ recipe.title }} <br>
      {% if recipe.time != -1 %}
        {{ recipe.time }} min <br>
      {% endif %}
      {% if recipe.recipe_yield %}
        {{ recipe.recipe_yield }} <br>
      {% endif %}
      {% if recipe.instructions %}
      <div> Instructions </div>
      <ol>
        {% for instruction in recipe.instructions %}
          <li>
            {{ instruction }}
          </li>
          {% endfor %}
      </ol>
      {% endif %}
      {% if recipe.original_url %}
        <a href={{ recipe.original_url }}> Original URL </a> <br>
      {% endif %}
      {% if ingredients %}
      <ul>
        {% for ingredient in ingredients %}
          <li>
            {{ ingredient.ingredient_info }}
          </li>
          {% endfor %}
      </ul>
      {% endif %}
      {% if images %}
        <ol>
        {% for img in images %}
           <li> <img src="{{ img.image.url }}" alt="img"> </li>
        {% endfor %}
        <ol>
      {% endif %}
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addImageModal">
        Add Image
      </button>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editRecipeModal">
        Edit Recipe
      </button>
    </div>
</div>

<!-- Modal -->
<div class="editRecipe-modal-wrapper">
  <div class="modal fade" id="editRecipeModal" tabindex="-1" aria-labelledby="editRecipeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <form method="post">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editRecipeModalLabel">Edit Recipe</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_title"> Recipe Title: </label>
              <div class="form-label-group">
                {{ edit_recipe_form.title }}
              </div>
              <label for="id_time"> Recipe Time (in minutes): </label>
              <div class="form-label-group">
                {{ edit_recipe_form.time }}
              </div>
              <label for="id_recipe_yield"> Recipe Yield: </label>
              <div class="form-label-group">
                {{ edit_recipe_form.recipe_yield }}
              </div>
              <label for="id_instructions"> Instructions (enter each step on a new line): </label>
              <div class="form-label-group">
                {{ edit_recipe_form.instructions }}
              </div>
              <label for="#formset_container"> Ingredients: </label>
              <div id="formset_container" class="form-label-group">
                {{ ingredient_formset.management_form }}
                {% for ingredient_form in ingredient_formset %}
                    <div class="ingredient-form py-1">
                        {{ ingredient_form.ingredient }}
                    </div>
                {% endfor %}
                <button id="add-form" class="btn btn-primary" type="button">Add Another Ingredient</button>
              </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" name="editRecipeSubmit" class="btn btn-primary">Save Changes</button>
        </div>
        </form>
      </div>
    </div>
 </div>

<div class="addImage-modal-wrapper">
  <div class="modal fade" id="addImageModal" tabindex="-1" aria-labelledby="addImageModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <form method="post" enctype="multipart/form-data" action="/addImage/{{ recipe.title }}">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addImageModalLabel">Add Image</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            {% csrf_token %}
            {{ image_upload_form.as_p }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" name="addImageSubmit" class="btn btn-primary">Add Image</button>
        </div>
        </form>
      </div>
    </div>
  </div>

  <script>
    document.getElementById("id_title").classList.add("form-control");
    document.getElementById("id_title").autofocus = "autofocus";
    document.getElementById("id_time").classList.add("form-control");
    document.getElementById("id_recipe_yield").classList.add("form-control");
    document.getElementById("id_instructions").classList.add("form-control");
  </script>

  <script>
    let allForm = document.querySelectorAll(".ingredient-form")
    let container = document.querySelector("#formset_container")
    let addButton = document.querySelector("#add-form")
    let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
    let formNum = allForm.length-1
    addButton.addEventListener('click', addForm)
    for (var i = 0; i < allForm.length; i++) {
      document.getElementById("id_form-" + i + "-ingredient").classList.add("form-control")
    }

    function addForm(e) {
        e.preventDefault()

        let newForm = allForm[0].cloneNode(true) //Clone the bird form
        let formRegex = RegExp(`form-(\\d){1}-`,'g') //Regex to find all instances of the form number

        formNum++ //Increment the form number
        newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`) //Update the new form to have the correct form number
        container.insertBefore(newForm, addButton) //Insert the new form at the end of the list of forms
        document.getElementById("id_form-" + formNum + "-ingredient").classList.add("form-control");
        document.getElementById("id_form-" + formNum + "-ingredient").value = "";
        totalForms.setAttribute('value', `${formNum+1}`) //Increment the number of total forms in the management form
      }
  </script>
{% endblock %}